language: node_js
node_js:
  - "4.5.0"
cache:
  directories:
    - node_modules
services: mongodb
script: npm run coverage
addons:
  code_climate:
    repo_token: efcb46a32e9cd070a83cef3311641eac476e2f856c588942fc3f1cace2ca5e64
after_script:
  - codeclimate-test-reporter < lcov.info
